"""
GitHub CI integration — annotations, step summary, output variables.

Writes GitHub Actions workflow commands to stdout so the runner
picks them up as inline PR annotations and step summary entries.
"""

from __future__ import annotations

import os
import sys


def _gha() -> bool:
    return os.environ.get("GITHUB_ACTIONS") == "true"


def annotate_finding(finding: dict, workspace: str = "") -> None:
    severity = finding.get("severity", "INFO").upper()
    file_path = finding.get("file", "")
    line = finding.get("line")
    title = finding.get("title", "Security Issue")
    description = finding.get("description", "")
    cwe = finding.get("cwe", "")

    # Strip workspace prefix for cleaner annotations
    if workspace and file_path.startswith(workspace):
        file_path = file_path[len(workspace):].lstrip("/")

    level = "error" if severity in ("CRITICAL", "HIGH") else "warning" if severity == "MEDIUM" else "notice"
    cwe_str = f" [{cwe}]" if cwe else ""
    msg = f"{description[:200]}" if description else title

    line_part = f",line={line}" if line else ""
    print(f"::{level} file={file_path}{line_part},title={title}{cwe_str}::{msg}")


def write_step_summary(results: dict) -> None:
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return

    all_findings = results.get("all_findings", [])
    severity_counts = results.get("severity_counts", {})
    target = results.get("target", ".")
    mode = results.get("mode", "both")
    duration = results.get("duration_seconds", 0)
    highest = results.get("highest_severity", "CLEAR")
    total = results.get("total_findings", 0)

    status_icon = {"CLEAR": "✅", "LOW": "🟡", "MEDIUM": "🟠", "HIGH": "🔴", "CRITICAL": "🚨"}.get(highest, "⚠️")

    lines = [
        f"# {status_icon} BASS Security Scan Report",
        f"",
        f"| | |",
        f"|---|---|",
        f"| **Target** | `{target}` |",
        f"| **Mode** | {mode.upper()} |",
        f"| **Duration** | {duration:.1f}s |",
        f"| **Status** | **{highest}** |",
        f"| **Total Findings** | {total} |",
        f"",
        f"## Severity Breakdown",
        f"",
        f"| Severity | Count |",
        f"|---|---|",
    ]

    severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    icons = {"CRITICAL": "🚨", "HIGH": "🔴", "MEDIUM": "🟠", "LOW": "🟡", "INFO": "🔵"}
    for sev in severity_order:
        count = severity_counts.get(sev, 0)
        icon = icons.get(sev, "")
        lines.append(f"| {icon} {sev} | {count} |")

    if all_findings:
        lines += [
            "",
            "## Findings",
            "",
            "| Severity | File | Line | Title | CWE | Source |",
            "|---|---|---|---|---|---|",
        ]
        for f in all_findings[:50]:
            sev = f.get("severity", "INFO").upper()
            icon = icons.get(sev, "")
            file_path = f.get("file", "")
            line = f.get("line", "—")
            title = f.get("title", "")[:60]
            cwe = f.get("cwe") or "—"
            source = f.get("_source", "")
            checkpoint = f.get("_checkpoint", "")
            src_label = f"{source}/{checkpoint}" if checkpoint else source
            lines.append(f"| {icon} {sev} | `{file_path}` | {line} | {title} | {cwe} | {src_label} |")

        if len(all_findings) > 50:
            lines.append(f"")
            lines.append(f"*...and {len(all_findings) - 50} more findings. See the full HTML report artifact.*")

    lines += ["", "---", "*Generated by [BASS — Base Alert Security System](https://github.com/DJ848arch/Claud-AI-Security-Tool)*"]

    with open(summary_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def set_outputs(results: dict) -> None:
    output_path = os.environ.get("GITHUB_OUTPUT")
    if not output_path:
        return
    total = results.get("total_findings", 0)
    highest = results.get("highest_severity", "CLEAR")
    with open(output_path, "a", encoding="utf-8") as fh:
        fh.write(f"findings-count={total}\n")
        fh.write(f"highest-severity={highest}\n")
        fh.write(f"report-path=bass-report.html\n")


def emit_all_annotations(results: dict) -> None:
    workspace = os.environ.get("GITHUB_WORKSPACE", "")
    for finding in results.get("all_findings", []):
        annotate_finding(finding, workspace)
